### ISSUE TITLE
Not showing the output image after the execution

### ISSUE THREAD

**Issue by Nayannsoni** [YP522/PicCheck#3]
no output after execution of this py file - pck.py run img1_path img2_path after the completion of execution the terminal will close

**Comment by YP522** [comment]
Hello Nayannsoni,

I have just re-installed the project and I don't see any problems when running the command.
An output folder should appear in the PicCheck project (next to the executable, generate, processing, system folders).

My version of python is 3.10.2, and I am on W10.

Normally in the terminal should appear the following line: 
` [PCK] Please see report at: output/DD-MM-YYYY-HH-MM-SS/report/report.html`

If the terminal suddenly shuts down, there is certainly a reason (error, permissions to create a directory, etc...)
Don't you have any error messages?

**Comment by Nayannsoni** [comment]
ok even if run PicCheck.Exe file then after uploading an image in both place & once i click on generate, a popup will come 'success report' once I click on ok then whole pic check windows closed, I am not getting any option to output here also

**Comment by YP522** [comment]
Hello Nayannsoni,

What is strange is that the program should fail if there is no output folder generated due to paths not being found.

But indeed, once you click on "ok", the program closes and nothing happens. You have to go to the output folder.

I will add features in the future such as opening the file explorer when clicking and the possibility to configure the output path.

Can you tell me if you have the output folder generated at the root as in the tutorial on the right: https://ypetit.web-edu.fr/piccheck/assets/pck_tuto.mp4

Thanks

**Comment by Nayannsoni** [comment]
yeah ok, now I got it, Thanks for the Video tutorial...
